### ISSUE TITLE
Improve 401 message

### ISSUE THREAD

**Issue by glennblock** [auth0/webtask-userspace#3]
Currently the auth middleware returns a 401 with a JSON object with the message "Unathenticated Extensibility Point".

Did we consider just returning a 401 without any message? This is very common for APIs and 401 Unauthorized is well understood.

Alternatively, I'd suggest we change the message indicate what is missing like "Missing or Invalid Bearer Token"

**Comment by NotMyself** [comment]
Hi @glennblock,

Thanks for the feedback. We will not be adding this functionality in the near future. I have added it to a list of feature requests to be evaluated in the future.

**Comment by glennblock** [comment]
The error message is confusing. The Extensibility point itself is not the issue, it is that the user did not provide proper auth to access it.
